[workspace]
members = [
	"client",
	"driver",
	"server",
	"integration-tests",
	"keygen",
	"lib/model",
	"lib/protos",
	"lib/tracing-utils",
	"lib/tracing-utils/tracing-utils-macros",
]

# make color-eyre fast
[profile.dev.package.backtrace]
opt-level = 3
